### ISSUE TITLE
Request: Add LICENSE to repo

### ISSUE THREAD

**Issue by qpwo** [MKA-Stem/netQWOP#1]
So other projects can use it  more easily

**Comment by mapinis** [comment]
Hi! When it comes to the license, what do you plan on using this repo for? It's an old hackathon project that hsnt been touched in a while.

**Comment by qpwo** [comment]
Could I include it as a free game in a mixed collection of paid and free games, with attribution?

It will need a good amount of modification because the games are 2-player P2P and mainly for mobile.

**Comment by qpwo** [comment]
A working hackathon project like this is actually pretty rare & useful.

**Comment by wgoodall01** [comment]
Sounds good to me. I'd love to see this project get used in something substantial!

I'm happy to license it under Apache or CC-BY-SA, if that works for you @qpwo.

**Comment by qpwo** [comment]
Thank you! Apache would be great, since parts of the app are not open-source. I'll link this repo and publish the changes.

**Comment by mapinis** [comment]
Just added, have fun with the project and good luck with your collection. Both @wgoodall01 and I would definitely appreciate to be credited by both name and a link to the repo if you can.

**Comment by qpwo** [comment]
```html
<p>
QWOP game originally by <span id="names"></span>.
<a href="https://github.com/MKA-Stem/netQWOP"/>Source</a>.
</p> 
<script>
document.getElementById("names").innerText = 
        Math.random() > 0.5 ? "Mark Apinis and William Goodall" : "William Goodall and Mark Apinis"
</script>
```

**Comment by qpwo** [comment]
Also Sloc, Loc, & Code estimates your project cost $40k to develop xd

![image](https://user-images.githubusercontent.com/10591373/123862193-0a391680-d8f6-11eb-8bd7-dd5fe94ed038.png)
